#ifndef SMARTCAM_VERSION_H
#define SMARTCAM_VERSION_H

#define SMARTCAM_VERSION_MAJOR 1
#define SMARTCAM_VERSION_MINOR 0
#define SMARTCAM_VERSION_PATCH 0

#define SMARTCAM_VERSION_STRING "1.0.0"

#endif // SMARTCAM_VERSION_H
